server:
  port : 8080

spring :
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/readmate?serverTimezone=Asia/Seoul
    username: root
    password: 1234
